services:
  - type: web
    name: backend-terabox
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
